---
title: "MERFISH_bench"
author: "Anonymous"
date: "2024-03-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(atlasClustering)
library(spatialLIBD)
library(Seurat)
library(magrittr)
library(tidyverse)
library(ggnewscale) # for new_scale_colour()
library(igraph)
library(scry)
library(scater)
library(parallel)
options(future.globals.maxSize = 4000 * 1024^2)
```

## Load MERFISH

```{r cars}
M_df <- read_csv("G://projects_bk/MERFISH/Moffitt_and_Bambah-Mukku_et_al_merfish_all_cells.csv")

# replace NA to 0
for(i in colnames(M_df)[10:170]){
  M_df[[i]][is.na(M_df[[i]])] <- 0
}

seu_ls <- list()

for(i in levels(as.factor(M_df$Animal_ID))){
  for(j in levels(as.factor(M_df$Bregma[M_df$Animal_ID==i]))){
    idx = M_df$Animal_ID==i & M_df$Bregma == j
    seu_ls[[paste0(i,"_",j)]] <- CreateSeuratObject(counts = M_df[idx,c(10:170)] %>% as.matrix() %>% `row.names<-`(M_df$Cell_ID[idx]) %>% t(),
                                    meta.data = M_df[idx,1:9] %>% as.data.frame %>% `row.names<-`(M_df$Cell_ID[idx]) %>% 
                                      mutate(coord_x = Centroid_X, coord_y = Centroid_Y))
  }
  
}


```

```{r}

seu_ls <- stage_1p(seu_ls, cor_threshold = 0.6, nn = 6, nn_2=20, cl_resolution = 10,
                     top_pcs = 5, cl_min=5, find_HVG = T, hvg = 120, cor_met = "PC",
                     edge_smoothing = T, use_glmpca = T, verbose = T, num_core = 6)

rtn_ls <- stage_2p(seu_ls, cl_key = "merged_cluster",
                  rtn_seurat = T, nn_2 = 10, method = "MNN",
                  top_pcs = 5, use_glmpca = T, rare_ct = "m", resolution = 1)

seu_ls <- assign_label(seu_ls, rtn_ls$cl_df, "MNN", 0.6, cl_key = "merged_cluster")


```

```{r}
# ARI Stat
ari_df <- data.frame(sample_id = names(seu_ls)) %>%
  mutate(animal_id = str_extract(sample_id,"[0-9]+_") %>% str_remove(pattern = "_"),
         Bregma = str_extract(sample_id,"_.+") %>% str_remove(pattern = "_"),
         ari = sapply(sample_id,
                      function(x){
                        mclust::adjustedRandIndex(seu_ls[[x]]$sec_cluster_MNN, seu_ls[[x]]$Cell_class)
                      }))
ggplot(ari_df, aes(x = animal_id, y = ari, fill = animal_id)) +
  geom_boxplot() + 
  theme_classic()

i = "29_0.11"
draw_slide_graph(seu_ls[[i]]@meta.data,
                 seu_ls[[i]]@misc[["edges"]],
                 0.6,"Cell_class")


```

```{r}
# Try rasterization










```


