---
title: "Xenium_pipeline"
author: "Anonymous"
date: "2024-02-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("~/GitHub/atlasscalespatialclustering/haowen_update/R/tileBoundaries.R")
library(atlasClustering)
library(MoleculeExperiment)
library(scater)
```

## Load Data


```{r}
# Rasterization

me <- readXenium("G:/projects_bk/FF_MouseBrain",
                 keepCols = "essential",
                 addBoundaries = "cell")

me <- tileBoundaries(me, tile_width = 80)


spe = countMolecules(me, boundariesAssay = "tiles")


spe <- addPerCellQCMetrics(spe)
spe <- spe[,spe$total > 0]

new_seu_xenium <- function(sel_assay="counts"){
  seu_ls <- list()
  #hvg_ls <- c()
  #sel_assay <- "logcounts" # counts logcounts
  
  for(i in unique(spe$sample_id)){
    idx <- spe$sample_id == i
    seu_ls[[i]] <- CreateSeuratObject(counts = spe@assays@data@listData[[sel_assay]][,idx],
                                      project = paste0("spe_",i),
                                      meta.data = data.frame(barcode = spe@colData@rownames[idx],
                                                             detected = spe@colData@listData[["detected"]][idx],
                                                             sample = spe@colData@listData$sample_id[idx],
                                                             coord_x = spe@int_colData@listData[["spatialCoords"]][idx,1],
                                                             coord_y = spe@int_colData@listData[["spatialCoords"]][idx,2]),
                                      min.features = 75)
    seu_ls[[i]] <- FindVariableFeatures(seu_ls[[i]], verbose = F)
    #hvg_ls <- unique(c(hvg_ls,VariableFeatures(seurat_ls[[i]])))
  }
  seu_ls
}


seu_ls <- new_seu_xenium()


for(sample_name in c("Sample_1","Sample_2","Sample_3")){
  seu_ls[[sample_name]] <- NormalizeData(seu_ls[[sample_name]], 
                                         normalization.method = "LogNormalize", scale.factor = 10000, verbose = F)
  seu_ls[[sample_name]] <- ScaleData(seu_ls[[sample_name]], features = row.names(seu_ls[[sample_name]]), verbose = F)
  seu_ls[[sample_name]] <- RunPCA(seu_ls[[sample_name]], features = row.names(seu_ls[[sample_name]]), verbose = F)
  #ElbowPlot(seu_obj, ndims = 30)
  seu_ls[[sample_name]] <- FindNeighbors(seu_ls[[sample_name]], dims = 1:15, verbose = F)
  seu_ls[[sample_name]] <- FindClusters(seu_ls[[sample_name]], resolution = 0.5, verbose = F)
  seu_ls[[sample_name]] <- RunUMAP(seu_ls[[sample_name]], dims = 1:15, verbose = F)
  
}

par(mfrow=c(1,3))
plot(density(seu_ls[["Sample_1"]]@meta.data[["detected"]]), main = "Sample_1 Counts Density")
plot(density(seu_ls[["Sample_2"]]@meta.data[["detected"]]), main = "Sample_2 Counts Density")
plot(density(seu_ls[["Sample_3"]]@meta.data[["detected"]]), main = "Sample_3 Counts Density")


par(mfrow=c(2,3)) 
plot(density(seu_ls[["Normal"]]@meta.data[["nCount_RNA"]]), main = "Normal Counts Density")
plot(density(seu_ls[["Glioblastoma"]]@meta.data[["nCount_RNA"]]), main = "Glioblastoma Counts Density")
plot(density(seu_ls[["Alzheimers"]]@meta.data[["nCount_RNA"]]), main = "Alzheimers Counts Density")


plot(density(seu_ls[["Normal"]]@meta.data[["nFeature_RNA"]]), main = "Normal Genes Density")
plot(density(seu_ls[["Glioblastoma"]]@meta.data[["nFeature_RNA"]]), main = "Glioblastoma Genes Density")
plot(density(seu_ls[["Alzheimers"]]@meta.data[["nFeature_RNA"]]), main = "Alzheimers Genes Density")

```

## Stage 1

```{r}
seu_ls <- stage_1(seu_ls,find_HVG = T, top_pcs = 8, cor_threshold = 0.6, edge_smoothing = T, nn = 8, use_glmpca = T, hvg = 300)


rtn_ls <- stage_2(seu_ls, cl_key = "merged_cluster",
                  rtn_seurat = T,
                  nn_2 = 5, 
                  method = "MNN",
                  top_pcs = 8, 
                  use_glmpca = T, 
                  rare_ct = "m", resolution = 1)

seu_ls <- assign_label(seu_ls, rtn_ls$cl_df, "MNN", cor_threshold = 0.6, cl_key = "merged_cluster")

ggarrange(plotlist = list("PC1"=draw_slide_graph(seu_ls[["Sample_1"]]@meta.data, col_sel = "seurat_clusters"),
                          "PC2"=draw_slide_graph(seu_ls[["Sample_2"]]@meta.data, col_sel = "seurat_clusters"),
                          "PC3"=draw_slide_graph(seu_ls[["Sample_3"]]@meta.data, col_sel = "seurat_clusters")),ncol = 3,nrow = 1)

ggarrange(plotlist = list("PC1"=DimPlot(seu_ls[["Sample_1"]], reduction = "umap"),
                          "PC2"=DimPlot(seu_ls[["Sample_2"]], reduction = "umap"),
                          "PC3"=DimPlot(seu_ls[["Sample_3"]], reduction = "umap")),ncol = 3,nrow = 1)




ggarrange(plotlist = list("MNN1"= draw_slide_graph(seu_ls[["Sample_1"]]@meta.data,NULL,NULL,"sec_cluster_MNN"),
                          "MNN2"= draw_slide_graph(seu_ls[["Sample_2"]]@meta.data,NULL,NULL,"sec_cluster_MNN"),
                          "MNN3"= draw_slide_graph(seu_ls[["Sample_3"]]@meta.data,NULL,NULL,"sec_cluster_MNN"),
                          "GT1"=  draw_slide_graph(seu_ls[["Sample_1"]]@meta.data,NULL,NULL,"seurat_clusters"),
                          "GT2"=  draw_slide_graph(seu_ls[["Sample_2"]]@meta.data,NULL,NULL,"seurat_clusters"),
                          "GT3"=  draw_slide_graph(seu_ls[["Sample_3"]]@meta.data,NULL,NULL,"seurat_clusters")),
          ncol = 3,nrow = 2)

marker_ls <- list()

for(sample_name in c("Normal","Glioblastoma","Alzheimers")){
  marker_ls[[sample_name]] <- FindAllMarkers(seu_ls[[sample_name]])
}

library(ggalluvial)


sample1 = "Alzheimers"
sample1 = "Normal"
sample2 = "Glioblastoma"

marker_ls[[sample1]]$cluster <- as.factor(marker_ls[[sample1]]$cluster)
marker_ls[[sample2]]$cluster <- as.factor(marker_ls[[sample2]]$cluster)

cmat <- matrix(0, 
               nrow = length(levels(marker_ls[[sample1]]$cluster)),
               ncol = length(levels(marker_ls[[sample2]]$cluster)),
               dimnames = list(paste0(sample1,"_",levels(marker_ls[[sample1]]$cluster)),
                               paste0(sample2,"_",levels(marker_ls[[sample2]]$cluster))))


for(i in levels(marker_ls[[sample1]]$cluster)){
  for(j in levels(marker_ls[[sample2]]$cluster)){
    cmat[which(levels(marker_ls[[sample1]]$cluster) == i),which(levels(marker_ls[[sample2]]$cluster) == j)] <- 
      (intersect(marker_ls[[sample1]]$gene[marker_ls[[sample1]]$cluster == i],
                marker_ls[[sample2]]$gene[marker_ls[[sample2]]$cluster == j]) %>% length())/(
                  union(marker_ls[[sample1]]$gene[marker_ls[[sample1]]$cluster == i],
                marker_ls[[sample2]]$gene[marker_ls[[sample2]]$cluster == j]) %>% length()
                )
  }
}

Heatmap(cmat, column_title = paste(sample1,"and",sample2,"Markers"),
        layer_fun = function(j, i, x, y, width, height, fill) {
        # since grid.text can also be vectorized
        grid.text(sprintf("%.2f", pindex(cmat, i, j)), x, y, 
            gp = gpar(fontsize = 10))
})

```

