---
title: "Fig2-STARmap_benchmark"
author: "Anonymous"
date: "2024-05-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(atlasClustering)
library(spatialLIBD)
library(Seurat)
library(magrittr)
library(tidyverse)
library(peakRAM)
library(BASS)
library(BayesSpace)
library(harmony)
options(future.globals.maxSize = 4000 * 1024^2)
```

## Load Datasets

```{r cars}
save_dir <- "D:/Documents/GitHub/atlasClustering/archived/benchmark_res"
source("~/GitHub/atlasClustering/example/analysis/benchmark_helper_func.R")
load("G:/projects_bk/starmap/mPFC/starmap_mpfc.RData")

# Convert to Seurat List
seurat_ls <- list()

for(i in names(starmap_cnts)){
  seurat_ls[[i]] <- CreateSeuratObject(counts = starmap_cnts[[i]],
                                       meta.data = starmap_info[[i]],project = i)
  seurat_ls[[i]]$coord_x <- seurat_ls[[i]]$x
  seurat_ls[[i]]$coord_y <- seurat_ls[[i]]$y
  seurat_ls[[i]]$row <- seurat_ls[[i]]$x
  seurat_ls[[i]]$col <- seurat_ls[[i]]$y
}

# convert to spe obj
library(SpatialExperiment)
library(SingleCellExperiment)


sce_ls <- lapply(seurat_ls, function(x) {as.SingleCellExperiment(x)})

combined_sce <- do.call(cbind, sce_ls)

# Convert the combined SCE object to a SpatialExperiment object
spe <- SpatialExperiment(
  assays = list(counts = assay(combined_sce, "counts")),
  rowData = rowData(combined_sce),
  colData = colData(combined_sce),
  reducedDims = reducedDims(combined_sce),
  spatialCoords = matrix(c(combined_sce@colData@listData[["x"]],
                           combined_sce@colData@listData[["y"]]),
                         ncol = 2, 
                         dimnames = list(combined_sce@colData@rownames,c("x","y"))) # Adjust this if you have spatial coordinates
)



```

## Benchmark

```{r }
# Prepare
bench_res <- data.frame(method = c("atlasClustering","PRECAST","Seurat","BayesSpace","BASS"),
                        tic = 0,
                        toc = 0,
                        time = 0,
                        mem = -1,
                        ari = -1,
                        ari_vec = "-",
                        nmi = -1,
                        nmi_vec = "-")
fig_ls <- list()

for(i in names(seurat_ls)){
  fig_ls[[paste0("GT_",i)]] <- draw_slide_bench(seurat_ls[[i]]$coord_x,
                                                seurat_ls[[i]]$coord_y,
                                                seurat_ls[[i]]$z,"Layer",i,
                                                pal = RColorBrewer::brewer.pal(4,"Set1"),
                                                flip = F)
}
saveRDS(fig_ls,"~/GitHub/atlasClustering/archived/STARmap_groundtruth.rds")
```



### atlasClustering

```{r }
mem_usage <- peakRAM(
      {
        tic <- Sys.time()
        seurat_ls <- stage_1(seurat_ls, cor_threshold = 0.7, nn = 6, nn_2=20, cl_resolution = 10,
                             top_pcs = 6, cl_min=5, find_HVG = F, cor_met = "PC",
                             edge_smoothing = T, use_glmpca = T, verbose = T, num_core = 6)
        
        rtn_ls <- stage_2(seurat_ls, cl_key = "merged_cluster",
                          rtn_seurat = T, nn_2 = 10, method = "MNN",
                          top_pcs = 10, use_glmpca = T, rare_ct = "m", resolution = 0.7)
        
        seurat_ls <- assign_label(seurat_ls, rtn_ls$cl_df, "MNN", 0.7, cl_key = "merged_cluster")
        toc <- Sys.time()
      }
)

bench_res <- rkd_res(bench_res,tic,toc,mem_usage,"atlasClustering",seurat_ls,"z","sec_cluster_MNN")

for(i in names(seurat_ls)){
  fig_ls[[paste0("AC_",i)]] <- draw_slide_bench(seurat_ls[[i]]$coord_x,
                                                seurat_ls[[i]]$coord_y,
                                                seurat_ls[[i]]$sec_cluster_MNN,"atlasClustering",i,flip = F)
}


#ggpubr::ggarrange(plotlist = fig_ls[1:6],
#                  nrow = 2,ncol = 3)

#draw_slide_graph(seurat_ls[[i]]@meta.data,
#                 seurat_ls[[i]]@misc[["edges"]],NULL,"z")

```


### PRECAST
```{r }
library(PRECAST)
gc()
mem_usage <- peakRAM(
 {
   tic <- Sys.time()
   seuInt <- suppressMessages(PRECAST_test(seurat_ls,k=4,gene_num = 160))
   toc <- Sys.time()
 }
)

layer_vec <- sapply(seq_along(seurat_ls),function(i){
  tmp_df <- data.frame(barcode = row.names(seuInt@meta.data) %>% 
                         str_sub(start = 1, end = 18) %>% .[seuInt@meta.data[["batch"]]==i])
  tmp_df <- left_join(tmp_df,
                      data.frame(barcode = colnames(seurat_ls[[names(seurat_ls)[i]]]),
                                 z = seurat_ls[[names(seurat_ls)[i]]]@meta.data[,"z"]), 
                      by="barcode")
  tmp_df$z
  
}) %>% unlist()

bench_res <- rkd_res(bench_res,tic,toc,mem_usage,"PRECAST",
                     label_vec = layer_vec, result_vec = seuInt@meta.data[["cluster"]], sample_vec = seuInt@meta.data[["batch"]])

for(i in names(seurat_ls)){
  idx = seuInt@meta.data[["batch"]] == which(names(seurat_ls)==i)
  fig_ls[[paste0("PC_",i)]] <- draw_slide_bench(seuInt@reductions[["position"]]@cell.embeddings[idx,2],
                                                seuInt@reductions[["position"]]@cell.embeddings[idx,1],
                                                seuInt@meta.data[["cluster"]][idx],"PRECAST",i,flip = T)
}

rm(seuInt)
gc()
```

### Seurat

```{r}

mem_usage <- peakRAM(
  {
     tic <- Sys.time()
     seurat_ls <- lapply(X = seurat_ls, FUN = function(x) {
       x <- NormalizeData(x)
       x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 160)
       })
     features <- SelectIntegrationFeatures(object.list = seurat_ls)
     seurat_ls <- lapply(X = seurat_ls, FUN = function(x) {
       x <- ScaleData(x, features = features, verbose = FALSE)
       x <- RunPCA(x, features = features, verbose = FALSE)
       })
     anchors <- FindIntegrationAnchors(object.list = seurat_ls, anchor.features = features, reduction = "rpca", verbose = F)
     seu_combined <- IntegrateData(anchorset = anchors, verbose = F)
     DefaultAssay(seu_combined) <- "integrated"

         # Run the standard workflow for visualization and clustering
     seu_combined <- ScaleData(seu_combined, verbose = FALSE)
     seu_combined <- RunPCA(seu_combined, npcs = 6, verbose = FALSE)
     #seu_combined <- RunUMAP(seu_combined, reduction = "pca", dims = 1:10)
     seu_combined <- FindNeighbors(seu_combined, reduction = "pca", dims = 1:6)
     seu_combined <- FindClusters(seu_combined, resolution = 0.2)
     toc <- Sys.time()
  }
)

bench_res <- rkd_res(bench_res,tic,toc,mem_usage,"Seurat",label_vec = seu_combined@meta.data[["z"]], 
                     result_vec = seu_combined@meta.data[["seurat_clusters"]],
                     sample_vec = lapply(names(seurat_ls),function(i)rep(i,ncol(seurat_ls[[i]])))%>%unlist)

for(i in names(seurat_ls)){
  idx = seu_combined@meta.data[["orig.ident"]] == i
  fig_ls[[paste0("SR_",i)]] <- draw_slide_bench(seu_combined@meta.data[["x"]][idx],
                                                seu_combined@meta.data[["y"]][idx],
                                                seu_combined@meta.data[["seurat_clusters"]][idx],"Seurat",i,flip = F)
}



```
### BayesSpace-skip for STARmap

### BASS

```{r}
mem_usage <- peakRAM(
  {
    tic <- Sys.time()
    set.seed(0)
    # Set up BASS object
    BASS <- createBASSObject(lapply(seurat_ls, 
                                    function(seu_obj){
                                      seu_obj@assays[["RNA"]]@layers[["counts"]] %>% 
                                        `colnames<-`(colnames(seu_obj)) %>% `row.names<-`(row.names(seu_obj))
                                      }), 
                             lapply(seurat_ls, 
                                    function(seu_obj){
                                      data.frame(x=seu_obj$x,
                                                 y=seu_obj$y,
                                                 row.names=colnames(seu_obj))
                                      }), 
                             C = 15, R = 4,
      beta_method = "SW")
    
    BASS <- BASS.preprocess(BASS, doLogNormalize = TRUE, doPCA = TRUE, scaleFeature = T, nPC = 20)
    
    # Run BASS algorithm
    BASS <- BASS.run(BASS)
    BASS <- BASS.postprocess(BASS)
    toc <- Sys.time()
  }
)

bench_res <- rkd_res(bench_res,tic,toc,mem_usage,"BASS",
                     label_vec  = seu_combined@meta.data[["z"]], 
                     result_vec = unlist(BASS@results$z),
                     sample_vec = lapply(names(seurat_ls),function(i)rep(i,ncol(seurat_ls[[i]])))%>%unlist)

for(i in names(seurat_ls)){
  fig_ls[[paste0("BA_",i)]] <- draw_slide_bench(seurat_ls[[i]]$x,
                                                seurat_ls[[i]]$y,
                                                as.factor(BASS@results$z[[which(names(seurat_ls) == i)]]),
                                                "BASS",i,flip = F)
}

```


## Generate Figures
```{r}
bench_res <- bench_res[-4,]
# ARI/NMI boxplot
fig_ls[["ARI_stat"]] <- ggplot(data.frame(method = rep(bench_res$method, each=length(seurat_ls)),
                                          ARI = sapply(bench_res$ari_vec,function(s)str_split(s,pattern = ",")) %>% 
                                            unlist %>% as.numeric()),
                               aes(x = method, y = ARI, fill = method)) + 
  geom_boxplot() + 
  theme_classic()

fig_ls[["NMI_stat"]] <- ggplot(data.frame(method = rep(bench_res$method, each=length(seurat_ls)),
                  NMI = sapply(bench_res$nmi_vec,function(s)str_split(s,pattern = ",")) %>% unlist %>% as.numeric()),
       aes(x = method, y = NMI, fill = method)) + 
  geom_boxplot() + 
  theme_classic()

# Time/Mem 
fig_ls[["Mem_stat"]] <- ggplot(data.frame(method = bench_res$method,
                  Mem = bench_res$mem),
       aes(x = method, y = Mem, fill = method)) + 
  geom_bar(stat = "identity",width = 0.5) + 
  theme_classic()

fig_ls[["Time_stat"]] <- ggplot(data.frame(method = bench_res$method,
                  Time_min = (bench_res$toc-bench_res$tic)/60),
       aes(x = method, y = Time_min, fill = method)) + 
  geom_bar(stat = "identity",width = 0.5) + 
  theme_classic()

# Sample Plot
pdf(file.path(save_dir, paste0(Sys.Date(),"_STARmap_Benchmark_results2.pdf")),width = 4*8,height = 4)
sample_id = names(seurat_ls)[1]

ggpubr::ggarrange(plotlist = list(fig_ls[[paste0("GT_",sample_id)]] + NoLegend(),
                                  fig_ls[[paste0("AC_",sample_id)]] + NoLegend(),
                                  fig_ls[[paste0("PC_",sample_id)]] + NoLegend(),
                                  fig_ls[[paste0("BA_",sample_id)]] + NoLegend(),
                                  fig_ls[["ARI_stat"]],fig_ls[["NMI_stat"]],fig_ls[["Time_stat"]],fig_ls[["Mem_stat"]]),
                  nrow = 1,ncol = 8)
dev.off()

# Export individual figure
for(i in 1:nrow(bench_res)){
  j = switch(bench_res$method[i],
             atlasClustering = "AC",
             PRECAST = "PC",
             Seurat = "SR",
             BayesSpace = "BS",
             BASS = "BA")
  # Running results
  pdf(file.path(save_dir, paste0(Sys.Date(),"_STARmap_Benchmark_",bench_res$method[i],"_res.pdf")),width = 8,height = 4)
  
  ggpubr::ggarrange(plotlist = lapply(names(seurat_ls),function(x){fig_ls[[paste0(j,"_",x)]] + NoLegend()}),
                    nrow = 1,ncol = 1) %>% print()
  dev.off()
}

# Ground Truth
pdf(file.path(save_dir, paste0(Sys.Date(),"_STARmap_Benchmark_ground_truth.pdf")),width = 8,height = 4)

ggpubr::ggarrange(plotlist = lapply(names(seurat_ls),function(x){fig_ls[[paste0("GT_",x)]]}),
                  nrow = 1,ncol = 1)
dev.off()

pdf(file.path(save_dir, paste0(Sys.Date(),"_STARmap_Benchmark_ARI_stat.pdf")),width = 6,height = 4)
fig_ls[["ARI_stat"]] %>% print()
dev.off()

pdf(file.path(save_dir, paste0(Sys.Date(),"_STARmap_Benchmark_NMI_stat.pdf")),width = 6,height = 4)
fig_ls[["NMI_stat"]] %>% print()
dev.off()

pdf(file.path(save_dir, paste0(Sys.Date(),"_STARmap_Benchmark_Time_stat.pdf")),width = 6,height = 4)
fig_ls[["Time_stat"]] %>% print()
dev.off()

pdf(file.path(save_dir, paste0(Sys.Date(),"_STARmap_Benchmark_Mem_stat.pdf")),width = 6,height = 4)
fig_ls[["Mem_stat"]] %>% print()
dev.off()

saveRDS(fig_ls, file.path(save_dir, paste0(Sys.Date(),"_STARmap_bench_fig.RDS")))
write_tsv(bench_res,file.path(save_dir, paste0(Sys.Date(),"_STARmap_bench_res.tsv")))

```


## Export seurat list

```{r}
saveRDS(seurat_ls,file.path(save_dir, paste0(Sys.Date(),"_STARmap_seurat_list.RDS")))
```




