---
title: "Fig4-AD_pathology"
author: "Anonymous"
date: "2024-06-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(atlasClustering)
library(Seurat)
library(ggpubr)

source("~/GitHub/atlasClustering/example/analysis/benchmark_helper_func.R")
```

## Load Datasets

```{r}
expr_mat <- read_csv("G://projects_bk/starmap/visual_1020/expression_matrix_raw.csv")
gene_vec <- unlist(expr_mat[,1])
expr_mat <- expr_mat[,-1] %>% as.matrix()
meta_df <- read_csv("G:/projects_bk/starmap/visual_1020/metadata.csv", skip = 1) %>% 
  `colnames<-`(read.csv(file = "G:/projects_bk/starmap/visual_1020/metadata.csv", nrows = 1,header = F))
meta_ls <- lapply(paste0("G:/projects_bk/starmap/visual_1020/spatial_",rep(c(8,13),each=4),
                        "months-",rep(c("control","disease"),times=2,each=2),"-replicate_",
                        rep(1:2,4),".csv"),
                  FUN = function(x){
                    read.csv(file = x, skip = 2) %>% `colnames<-`(read.csv(file = x, nrows = 1,header = F))
                  })

tmp_df <- do.call(rbind.data.frame, meta_ls)


meta_df <- left_join(meta_df,tmp_df[,-6],by = "NAME")

plaque_df_8 <- read_csv("G:/projects_bk/starmap/visual_1020/plaque_8months-disease-replicate_1.csv")
plaque_df_13 <- read_csv("G:/projects_bk/starmap/visual_1020/plaque_13months-disease-replicate_1.csv")


```

## Remove cells w/o coords

```{r}
expr_mat <- expr_mat[,!is.na(meta_df$X)]
meta_df <- meta_df[!is.na(meta_df$X),] %>% as.data.frame()

sample_vec <- levels(as.factor(meta_df$biosample_id))

colnames(expr_mat) <- paste0(meta_df$biosample_id,"_",meta_df$NAME)
row.names(expr_mat) <- gene_vec
row.names(meta_df)<- paste0(meta_df$biosample_id,"_",meta_df$NAME)

colnames(meta_df)[23:24] <- c("coord_x","coord_y")

seu_ls <- lapply(sample_vec,
                 FUN = function(x){
                   suppressWarnings(CreateSeuratObject(counts = expr_mat[,meta_df$biosample_id == x],
                                      meta.data = meta_df[meta_df$biosample_id == x,]))
                 })

names(seu_ls) <- sample_vec %>% str_remove(pattern = "ADmouse_")
```

## Run Pipeline

```{r}
# Only on AD sample
sel_sample <- c("9735_brain","9723_brain",
                "9498_brain","9494_brain")
seu_ls <- seu_ls[sel_sample]

seu_ls <- stage_1(seu_ls, cor_threshold = 0.8, nn = 8, nn_2=20, cl_resolution = 10,
                     top_pcs = 8, cl_min=5, find_HVG = T, hvg = 2000, cor_met = "PC",
                     edge_smoothing = T, use_glmpca = T, verbose = T)
# perform state 2 of atlasclustering
rtn_ls <- stage_2(seu_ls, cl_key = "merged_cluster",
                  rtn_seurat = T, nn_2 = 10, method = "MNN",
                  top_pcs = 8, use_glmpca = T, rare_ct = "m", resolution = 2)

# assign labels from the two stages of atlasclustering
seu_ls <- assign_label(seu_ls, rtn_ls$cl_df, "MNN", 0.8, cl_key = "merged_cluster")

# Save results
#saveRDS(seu_ls,"STARmap_cl.RDS")
#saveRDS(rtn_ls,"STARmap_stage2_res.RDS")
seu_ls <- lapply(X = seu_ls, FUN = function(x) {
       x <- NormalizeData(x)
       x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
       })

seu_ls <- lapply(X = seu_ls, FUN = function(x) {
  x <- ScaleData(x, features = VariableFeatures(x), verbose = FALSE)
  x <- RunPCA(x, features = VariableFeatures(x), verbose = FALSE)
  })

```

## Visualization

```{r}


ggplot(rtn_ls$cl_df,aes(x=umap_1, y=umap_2,color=sample)) + 
  geom_point()+
  theme_classic()

ggplot(rtn_ls$cl_df,aes(x=umap_1, y=umap_2,color=louvain)) + 
    geom_point()+
    scale_color_manual(values = cl_pal)+
    theme_classic()

ggarrange(plotlist = lapply(sel_sample,
                            FUN = function(x){
                              ggplot(seu_ls[[x]]@misc[["edges"]],aes(x=weight))+
                                stat_ecdf(geom = "step") + 
                                theme_classic() + 
                                labs(title = x)
                            }),
          ncol = 2,nrow = 2)

cl_pal <- c("#D9D9D9", "#BC80BD", "#CCEBC5",RColorBrewer::brewer.pal(7,"Set3")) %>% `names<-`(levels(as.factor(rtn_ls$cl_df$louvain)))

# Combined with plaque
seu_ls[["9494_brain"]]@misc[["graph_plot_cluster_sec_MNN"]]+
  scale_color_manual(values = cl_pal) + 
  geom_point(data = plaque_df_13, mapping = aes(x=m.cx/0.3,y=m.cy/0.3), color = "blue")

seu_ls[["9723_brain"]]@misc[["graph_plot_cluster_sec_MNN"]]+
  scale_color_manual(values = cl_pal) + 
  geom_point(data = plaque_df_8, mapping = aes(x=m.cx/0.3,y=m.cy/0.3), color = "blue")

ggarrange(plotlist = lapply(names(seu_ls),
                            FUN = function(x)seu_ls[[x]]@misc[["graph_plot_cluster_sec_MNN"]]+
                              scale_color_manual(values = cl_pal)),
          ncol = 2,nrow = 2)




ct_pal <- c(RColorBrewer::brewer.pal(6,"Pastel1"),RColorBrewer::brewer.pal(7,"Pastel2")) %>% 
  `names<-`(levels(as.factor(meta_df$top_level_cell_type.x)))

ggplot(seu_ls[["9494_brain"]]@meta.data,aes(x = coord_y,y=coord_x,color=top_level_cell_type.x))+
                                geom_point()+
                                theme_classic()+
                                scale_color_manual(values = ct_pal) + 
  geom_point(data = plaque_df_13, mapping = aes(y=m.cx/0.3,x=m.cy/0.3), color = "blue")
ggplot(seu_ls[["9723_brain"]]@meta.data,aes(x = coord_y,y=coord_x,color=top_level_cell_type.x))+
                                geom_point()+
                                theme_classic()+
                                scale_color_manual(values = ct_pal) + 
  geom_point(data = plaque_df_8, mapping = aes(y=m.cx/0.3,x=m.cy/0.3), color = "blue")

ggarrange(plotlist = lapply(sel_sample,
                            FUN = function(x){
                              ggplot(seu_ls[[x]]@meta.data,aes(x = coord_y,y=coord_x,color=top_level_cell_type.x))+
                                geom_point()+
                                theme_classic()+
                                labs(title = x)+
                                scale_color_manual(values = ct_pal)
                            }),
          ncol = 2,nrow = 2)

plotConfusionMatrix(seu_ls[["9494_brain"]]@meta.data$sec_cluster_MNN,
                    seu_ls[["9494_brain"]]@meta.data$top_level_cell_type.x,
                    "9494_brain")

plotConfusionMatrix(lapply(seu_ls,function(seu_obj){seu_obj$sec_cluster_MNN}) %>% unlist() %>% as.numeric(),
                    lapply(seu_ls,function(seu_obj){seu_obj$top_level_cell_type.x}) %>% unlist(),
                    "MNN vs Cell Type", viridis::rocket(5, direction = -1))

plotConfusionMatrix(lapply(seu_ls,function(seu_obj){seu_obj$sec_cluster_MNN}) %>% unlist() %>% as.numeric(),
                    lapply(seu_ls,function(seu_obj){paste(seu_obj$group,seu_obj$time)}) %>% unlist(),
                    "MNN vs Condition", viridis::rocket(5, direction = -1))


```


## Findmarkers

```{r}
rtn_ls[["seurat_obj"]]@meta.data[["sec_cluster_MNN"]] <- rtn_ls[["cl_df"]][["louvain"]]
Idents(rtn_ls[["seurat_obj"]]) <- rtn_ls[["seurat_obj"]]@meta.data[["sec_cluster_MNN"]]
#marker_ls <- FindAllMarkers(seu_combined)
rtn_ls[["seurat_obj"]] <- NormalizeData(rtn_ls[["seurat_obj"]])
rtn_ls[["seurat_obj"]] <- FindVariableFeatures(rtn_ls[["seurat_obj"]], selection.method = "vst", nfeatures = 2000)
rtn_ls[["seurat_obj"]] <- ScaleData(rtn_ls[["seurat_obj"]], features = VariableFeatures(rtn_ls[["seurat_obj"]]), verbose = FALSE)
rtn_ls[["seurat_obj"]] <- RunPCA(rtn_ls[["seurat_obj"]], features = VariableFeatures(rtn_ls[["seurat_obj"]]), verbose = FALSE)



all_markers <- FindAllMarkers(rtn_ls[["seurat_obj"]],features = VariableFeatures(rtn_ls[["seurat_obj"]]),logfc.threshold = 0)
plot_ls <- list()
for(i in levels(as.factor(rtn_ls[["seurat_obj"]]$sec_cluster_MNN))){
  plot_ls[[paste0("cl_",i)]] <- ggplot(all_markers %>% subset(cluster == i & pct.1 > 0.1 & pct.2 > 0.1) %>% 
                                         mutate(de = ifelse(p_val_adj < 0.01 & abs(avg_log2FC) > .1,ifelse(avg_log2FC > 0,"UP","DOWN"),"NO")),
       aes(x = avg_log2FC, y = -log10(p_val_adj), color = de)) +
    geom_point() +
    labs(title = paste("Cluster",i)) +
    xlim(max(abs(all_markers$avg_log2FC))) + 
    scale_color_manual(values = c("UP" = "green", "DOWN" = "red","NO" = "grey")) +
    theme_classic()
}

ggpubr::ggarrange(plotlist = plot_ls,nrow = 3,ncol = 4)

# load PIGs
PIG_13mo <- read.csv("G://projects_bk/starmap/visual_1020/PIG_13mo.csv")[,1:3] %>% `colnames<-`(c("gene","cl","pval")) %>% 
  subset(cl %in% c("Cluster_1","Cluster_2","Cluster_3") & pval < 0.0001)

cl9_marker <- all_markers %>% subset(cluster == 6 & avg_log2FC > 0.1) %>% arrange(desc(avg_log2FC))

library(ggVennDiagram)

ggVennDiagram(list(PIG = PIG_13mo$gene, cl_9 = cl9_marker$gene))


ggplot(all_markers %>% subset(cluster == i & pct.1 > 0.1 & pct.2 > 0.1) %>% 
                                         mutate(de = ifelse(p_val_adj < 0.01 & abs(avg_log2FC) > .1,ifelse(avg_log2FC > 0,"UP","DOWN"),"NO"),
                                                de_label = ifelse(gene %in% PIG_13mo$gene & de == "UP", gene, NA)),
       aes(x = avg_log2FC, y = -log10(p_val_adj), color = de, label = de_label)) +
    geom_point() +
    ggrepel::geom_text_repel() +
    labs(title = paste("Cluster",i)) +
    xlim(-3,3) + 
    scale_color_manual(values = c("UP" = "red", "DOWN" = "blue","NO" = "grey")) +
    theme_classic()

# Pathway Analysis
library(gprofiler2)
gostres <- gost(query = all_markers %>% subset(cluster == 6 & avg_log2FC > 0.1) %>% .$gene,
                organism = "mmusculus")

ggplot(gostres$result %>% subset(source == "GO:BP") %>% 
         mutate(p_adj = p.adjust(p_value)) %>% subset(p_adj < 0.01),
       aes(x = -log10(p_adj), y = term_name)) + 
  geom_bar(fill = "brown", stat = "identity")


```

## Colocalization 

```{r}

get_plaque_summ <- function(combined_df, max_dist){
  nn <- dbscan::kNN(combined_df[,1:2],100)
  message(paste("Min-max distance in NN:",apply(nn[["dist"]],1,max) %>% min()))
  
  combined_df$plaque <- sapply(1:nrow(combined_df),
                              function(x){
                                if(combined_df$label[x] == "plaque" | is.na(combined_df$label[x]))0
                                else{
                                  sum(nn$id[x,nn$dist[x,] <= max_dist ] %in% which(combined_df$label == "plaque"))
                                }
                              })
  combined_df %>% subset(label != "plaque" & !is.na(label)) %>% group_by(label) %>% 
    summarise(mean_plaque = mean(plaque)) %>% mutate(label = as.numeric(label)) %>% arrange(label) %>% .$mean_plaque
}

max_dist = 30*10 #20um

summ_df <- data.frame(cluster=rtn_ls[["cl_df"]]$louvain %>% na.omit() %>% unique() %>% as.numeric() %>% sort())

combined_df <- data.frame(x = c(seu_ls[["9494_brain"]]@meta.data[["coord_x"]],
                                plaque_df_13$m.cx/0.3),
                          y = c(seu_ls[["9494_brain"]]@meta.data[["coord_y"]],
                                plaque_df_13$m.cy/0.3),
                          label = c(seu_ls[["9494_brain"]]@meta.data[["sec_cluster_MNN"]],
                                    rep("plaque", nrow(plaque_df_13))))
summ_df$plaque_13mo <- get_plaque_summ(combined_df, max_dist)


combined_df <- data.frame(x = c(seu_ls[["9723_brain"]]@meta.data[["coord_x"]],
                                plaque_df_8$m.cx/0.3),
                          y = c(seu_ls[["9723_brain"]]@meta.data[["coord_y"]],
                                plaque_df_8$m.cy/0.3),
                          label = c(seu_ls[["9723_brain"]]@meta.data[["sec_cluster_MNN"]],
                                    rep("plaque", nrow(plaque_df_8))))
summ_df$plaque_8mo <- get_plaque_summ(combined_df, max_dist)

Heatmap(as.matrix(summ_df[,2:3]) %>% `row.names<-`(summ_df$cluster),
        col = circlize::colorRamp2(seq(0, max(summ_df[,2:3]), length.out = 5), viridis::viridis(5)),
        cluster_rows = F, cluster_columns = F,rect_gp = grid::gpar(col = "white", lwd = 1))


```


## Save RDS

```{r}
save_dir <- "D:/Documents/GitHub/atlasClustering/archived/analysis_res"
save(list = c("seu_ls","rtn_ls"), file = file.path(save_dir, paste0(Sys.Date(),"_STARmap_AD.RData"))) 


```
